/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type Tier = {
  _type: 'tier'
  name: string
  price: string
  period?: string
  description: string
  features: Array<string>
  cta: Link
  highlighted?: boolean
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Testimonial = {
  _type: 'testimonial'
  quote: string
  name: string
  role: string
  affiliation?: string
  avatar: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
  }
}

export type Seo = {
  _type: 'seo'
  title: string
  description: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Link = {
  _type: 'link'
  label: string
  href: string
}

export type Highlight = {
  _type: 'highlight'
  icon: 'dome' | 'telescope' | 'orbit' | 'comet' | 'moon' | 'school'
  title: string
  body: string
}

export type Hero = {
  _type: 'hero'
  eyebrow?: string
  heading: string
  tagline: string
  primaryCta: Link
  secondaryCta?: Link
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
  }
}

export type CallToAction = {
  _type: 'callToAction'
  heading: string
  body?: string
  cta: Link
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  siteTitle: string
  nav: Array<
    {
      _key: string
    } & Link
  >
  footerTagline: string
  footerLinks: Array<
    {
      _key: string
    } & Link
  >
}

export type VisitPage = {
  _id: string
  _type: 'visitPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  heading: string
  tagline: string
  tiers: Array<
    {
      _key: string
    } & Tier
  >
  seo: Seo
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  hero: Hero
  partnersHeading: string
  partners: Array<string>
  highlightsHeading: string
  highlights: Array<
    {
      _key: string
    } & Highlight
  >
  testimonial: Testimonial
  cta: CallToAction
  seo: Seo
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type AllSanitySchemaTypes =
  | Tier
  | SanityImageAssetReference
  | Testimonial
  | Seo
  | Link
  | Highlight
  | Hero
  | CallToAction
  | SiteSettings
  | VisitPage
  | HomePage
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug

// Source: ../observatory/src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{  siteTitle,  nav,  footerTagline,  footerLinks}
export type SITE_SETTINGS_QUERY_RESULT = {
  siteTitle: string
  nav: Array<
    {
      _key: string
    } & Link
  >
  footerTagline: string
  footerLinks: Array<
    {
      _key: string
    } & Link
  >
} | null

// Source: ../observatory/src/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage" && _id == "homePage"][0]{  hero{    eyebrow,    heading,    tagline,    primaryCta,    secondaryCta,    image {  alt,  hotspot,  crop,  asset->{_id, url, mimeType, metadata{dimensions{width, height, aspectRatio}}}}  },  partnersHeading,  partners,  highlightsHeading,  highlights[]{icon, title, body},  testimonial{    quote,    name,    role,    affiliation,    avatar {  alt,  hotspot,  crop,  asset->{_id, url, mimeType, metadata{dimensions{width, height, aspectRatio}}}}  },  cta{heading, body, cta},  seo{title, description, ogImage{hotspot, crop, asset->{_id, url}}}}
export type HOME_PAGE_QUERY_RESULT = {
  hero: {
    eyebrow: string | null
    heading: string
    tagline: string
    primaryCta: Link
    secondaryCta: Link | null
    image: {
      alt: string
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      asset: {
        _id: string
        url: string
        mimeType: string
        metadata: {
          dimensions: {
            width: number
            height: number
            aspectRatio: number
          } | null
        } | null
      } | null
    }
  }
  partnersHeading: string
  partners: Array<string>
  highlightsHeading: string
  highlights: Array<{
    icon: 'comet' | 'dome' | 'moon' | 'orbit' | 'school' | 'telescope'
    title: string
    body: string
  }>
  testimonial: {
    quote: string
    name: string
    role: string
    affiliation: string | null
    avatar: {
      alt: string
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      asset: {
        _id: string
        url: string
        mimeType: string
        metadata: {
          dimensions: {
            width: number
            height: number
            aspectRatio: number
          } | null
        } | null
      } | null
    }
  }
  cta: {
    heading: string
    body: string | null
    cta: Link
  }
  seo: {
    title: string
    description: string
    ogImage: {
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      asset: {
        _id: string
        url: string
      } | null
    } | null
  }
} | null

// Source: ../observatory/src/sanity/queries.ts
// Variable: VISIT_PAGE_QUERY
// Query: *[_type == "visitPage" && _id == "visitPage"][0]{  heading,  tagline,  tiers[]{name, price, period, description, features, cta, highlighted},  seo{title, description, ogImage{hotspot, crop, asset->{_id, url}}}}
export type VISIT_PAGE_QUERY_RESULT = {
  heading: string
  tagline: string
  tiers: Array<{
    name: string
    price: string
    period: string | null
    description: string
    features: Array<string>
    cta: Link
    highlighted: boolean | null
  }>
  seo: {
    title: string
    description: string
    ogImage: {
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      asset: {
        _id: string
        url: string
      } | null
    } | null
  }
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "siteSettings" && _id == "siteSettings"][0]{\n  siteTitle,\n  nav,\n  footerTagline,\n  footerLinks\n}': SITE_SETTINGS_QUERY_RESULT
    '*[_type == "homePage" && _id == "homePage"][0]{\n  hero{\n    eyebrow,\n    heading,\n    tagline,\n    primaryCta,\n    secondaryCta,\n    image {\n  alt,\n  hotspot,\n  crop,\n  asset->{_id, url, mimeType, metadata{dimensions{width, height, aspectRatio}}}\n}\n  },\n  partnersHeading,\n  partners,\n  highlightsHeading,\n  highlights[]{icon, title, body},\n  testimonial{\n    quote,\n    name,\n    role,\n    affiliation,\n    avatar {\n  alt,\n  hotspot,\n  crop,\n  asset->{_id, url, mimeType, metadata{dimensions{width, height, aspectRatio}}}\n}\n  },\n  cta{heading, body, cta},\n  seo{title, description, ogImage{hotspot, crop, asset->{_id, url}}}\n}': HOME_PAGE_QUERY_RESULT
    '*[_type == "visitPage" && _id == "visitPage"][0]{\n  heading,\n  tagline,\n  tiers[]{name, price, period, description, features, cta, highlighted},\n  seo{title, description, ogImage{hotspot, crop, asset->{_id, url}}}\n}': VISIT_PAGE_QUERY_RESULT
  }
}
