/**
 * This file is generated from Sanity typegen output.
 * Regenerate with: pnpm sanity:live:schemas
 */

// Generated by ts-to-zod
import { z } from 'astro/zod';

export const sanitySlugSchema = z.object({
    _type: z.literal("slug"),
    current: z.string().optional()
});

export const sanityReferenceSchema = z.object({
    _type: z.literal("reference"),
    _ref: z.string()
});

export const sanityImageSchema = z.object({
    _type: z.literal("image"),
    asset: sanityReferenceSchema.optional()
});

export const personDocumentSchema = z.object({
    _id: z.string(),
    _type: z.literal("person"),
    _createdAt: z.string().optional(),
    _updatedAt: z.string().optional(),
    name: z.string().optional(),
    slug: sanitySlugSchema.optional(),
    image: sanityImageSchema.optional()
});

export const movieDocumentSchema = z.object({
    _id: z.string(),
    _type: z.literal("movie"),
    _createdAt: z.string().optional(),
    _updatedAt: z.string().optional(),
    title: z.string().optional(),
    slug: sanitySlugSchema.optional(),
    releaseDate: z.string().optional(),
    poster: sanityImageSchema.optional()
});

export const screeningDocumentSchema = z.object({
    _id: z.string(),
    _type: z.literal("screening"),
    _createdAt: z.string().optional(),
    _updatedAt: z.string().optional(),
    title: z.string().optional(),
    movie: sanityReferenceSchema.optional(),
    published: z.boolean().optional(),
    beginAt: z.string().optional(),
    endAt: z.string().optional(),
    infoUrl: z.string().optional()
});
