/**
 * This file is generated from Sanity typegen output.
 * Regenerate with: pnpm sanity:live:schemas
 */

// Generated by ts-to-zod
import { z } from 'astro/zod';

export const personReferenceSchema = z.object({
    _ref: z.string(),
    _type: z.literal("reference"),
    _weak: z.boolean().optional()
});

export const crewMemberSchema = z.object({
    _type: z.literal("crewMember"),
    department: z.string().optional(),
    job: z.string().optional(),
    person: personReferenceSchema.optional(),
    externalId: z.number().optional(),
    externalCreditId: z.string().optional()
});

export const castMemberSchema = z.object({
    _type: z.literal("castMember"),
    characterName: z.string().optional(),
    person: personReferenceSchema.optional(),
    externalId: z.number().optional(),
    externalCreditId: z.string().optional()
});

export const plotSummarySchema = z.object({
    _type: z.literal("plotSummary"),
    summary: z.string().optional(),
    author: z.string().optional(),
    url: z.string().optional()
});

export const sanityImageAssetReferenceSchema = z.object({
    _ref: z.string(),
    _type: z.literal("reference"),
    _weak: z.boolean().optional()
});

export const sanityImageHotspotSchema = z.object({
    _type: z.literal("sanity.imageHotspot"),
    x: z.number().optional(),
    y: z.number().optional(),
    height: z.number().optional(),
    width: z.number().optional()
});

export const sanityImageCropSchema = z.object({
    _type: z.literal("sanity.imageCrop"),
    top: z.number().optional(),
    bottom: z.number().optional(),
    left: z.number().optional(),
    right: z.number().optional()
});

export const movieReferenceSchema = z.object({
    _ref: z.string(),
    _type: z.literal("reference"),
    _weak: z.boolean().optional()
});

export const sanityFileAssetReferenceSchema = z.object({
    _ref: z.string(),
    _type: z.literal("reference"),
    _weak: z.boolean().optional()
});

export const geopointSchema = z.object({
    _type: z.literal("geopoint"),
    lat: z.number().optional(),
    lng: z.number().optional(),
    alt: z.number().optional()
});

export const slugSchema = z.object({
    _type: z.literal("slug"),
    current: z.string().optional(),
    source: z.string().optional()
});

export const blockContentSchema = z.array(z.union([z.object({
        children: z.array(z.object({
            marks: z.array(z.string()).optional(),
            text: z.string().optional(),
            _type: z.literal("span"),
            _key: z.string()
        })).optional(),
        style: z.union([z.literal("normal"), z.literal("h1"), z.literal("h2"), z.literal("h3"), z.literal("h4"), z.literal("blockquote")]).optional(),
        listItem: z.literal("bullet").optional(),
        markDefs: z.array(z.object({
            href: z.string().optional(),
            _type: z.literal("link"),
            _key: z.string()
        })).optional(),
        level: z.number().optional(),
        _type: z.literal("block"),
        _key: z.string()
    }), z.object({
        asset: sanityImageAssetReferenceSchema.optional(),
        media: z.unknown().optional(),
        hotspot: sanityImageHotspotSchema.optional(),
        crop: sanityImageCropSchema.optional(),
        _type: z.literal("image"),
        _key: z.string()
    })]));

export const sanityImagePaletteSwatchSchema = z.object({
    _type: z.literal("sanity.imagePaletteSwatch"),
    background: z.string().optional(),
    foreground: z.string().optional(),
    population: z.number().optional(),
    title: z.string().optional()
});

export const sanityImagePaletteSchema = z.object({
    _type: z.literal("sanity.imagePalette"),
    darkMuted: sanityImagePaletteSwatchSchema.optional(),
    lightVibrant: sanityImagePaletteSwatchSchema.optional(),
    darkVibrant: sanityImagePaletteSwatchSchema.optional(),
    vibrant: sanityImagePaletteSwatchSchema.optional(),
    dominant: sanityImagePaletteSwatchSchema.optional(),
    lightMuted: sanityImagePaletteSwatchSchema.optional(),
    muted: sanityImagePaletteSwatchSchema.optional()
});

export const sanityImageDimensionsSchema = z.object({
    _type: z.literal("sanity.imageDimensions"),
    height: z.number().optional(),
    width: z.number().optional(),
    aspectRatio: z.number().optional()
});

export const sanityImageMetadataSchema = z.object({
    _type: z.literal("sanity.imageMetadata"),
    location: geopointSchema.optional(),
    dimensions: sanityImageDimensionsSchema.optional(),
    palette: sanityImagePaletteSchema.optional(),
    lqip: z.string().optional(),
    blurHash: z.string().optional(),
    hasAlpha: z.boolean().optional(),
    isOpaque: z.boolean().optional()
});

export const sanityAssetSourceDataSchema = z.object({
    _type: z.literal("sanity.assetSourceData"),
    name: z.string().optional(),
    id: z.string().optional(),
    url: z.string().optional()
});

export const sanityImageAssetSchema = z.object({
    _id: z.string(),
    _type: z.literal("sanity.imageAsset"),
    _createdAt: z.string(),
    _updatedAt: z.string(),
    _rev: z.string(),
    originalFilename: z.string().optional(),
    label: z.string().optional(),
    title: z.string().optional(),
    description: z.string().optional(),
    altText: z.string().optional(),
    sha1hash: z.string().optional(),
    extension: z.string().optional(),
    mimeType: z.string().optional(),
    size: z.number().optional(),
    assetId: z.string().optional(),
    uploadId: z.string().optional(),
    path: z.string().optional(),
    url: z.string().optional(),
    metadata: sanityImageMetadataSchema.optional(),
    source: sanityAssetSourceDataSchema.optional()
});

export const plotSummariesSchema = z.object({
    _type: z.literal("plotSummaries"),
    caption: z.string().optional(),
    summaries: z.array(z.object({
        _key: z.string()
    }).and(plotSummarySchema)).optional()
});

export const screeningSchema = z.object({
    _id: z.string(),
    _type: z.literal("screening"),
    _createdAt: z.string(),
    _updatedAt: z.string(),
    _rev: z.string(),
    title: z.string().optional(),
    movie: movieReferenceSchema.optional(),
    published: z.boolean().optional(),
    location: geopointSchema.optional(),
    beginAt: z.string().optional(),
    endAt: z.string().optional(),
    allowedGuests: z.union([z.literal("members"), z.literal("friends"), z.literal("anyone")]).optional(),
    infoUrl: z.string().optional(),
    ticket: z.object({
        asset: sanityFileAssetReferenceSchema.optional(),
        media: z.unknown().optional(),
        _type: z.literal("file")
    }).optional()
});

export const personSchema = z.object({
    _id: z.string(),
    _type: z.literal("person"),
    _createdAt: z.string(),
    _updatedAt: z.string(),
    _rev: z.string(),
    name: z.string().optional(),
    slug: slugSchema.optional(),
    image: z.object({
        asset: sanityImageAssetReferenceSchema.optional(),
        media: z.unknown().optional(),
        hotspot: sanityImageHotspotSchema.optional(),
        crop: sanityImageCropSchema.optional(),
        _type: z.literal("image")
    }).optional()
});

export const movieSchema = z.object({
    _id: z.string(),
    _type: z.literal("movie"),
    _createdAt: z.string(),
    _updatedAt: z.string(),
    _rev: z.string(),
    title: z.string().optional(),
    slug: slugSchema.optional(),
    overview: blockContentSchema.optional(),
    releaseDate: z.string().optional(),
    poster: z.object({
        asset: sanityImageAssetReferenceSchema.optional(),
        media: z.unknown().optional(),
        hotspot: sanityImageHotspotSchema.optional(),
        crop: sanityImageCropSchema.optional(),
        _type: z.literal("image")
    }).optional(),
    externalId: z.number().optional(),
    popularity: z.number().optional(),
    castMembers: z.array(z.object({
        _key: z.string()
    }).and(castMemberSchema)).optional(),
    crewMembers: z.array(z.object({
        _key: z.string()
    }).and(crewMemberSchema)).optional()
});

export const sanityFileAssetSchema = z.object({
    _id: z.string(),
    _type: z.literal("sanity.fileAsset"),
    _createdAt: z.string(),
    _updatedAt: z.string(),
    _rev: z.string(),
    originalFilename: z.string().optional(),
    label: z.string().optional(),
    title: z.string().optional(),
    description: z.string().optional(),
    altText: z.string().optional(),
    sha1hash: z.string().optional(),
    extension: z.string().optional(),
    mimeType: z.string().optional(),
    size: z.number().optional(),
    assetId: z.string().optional(),
    uploadId: z.string().optional(),
    path: z.string().optional(),
    url: z.string().optional(),
    source: sanityAssetSourceDataSchema.optional()
});

export const sanityLiveLoadermovieCollectionQueryResultSchema = z.array(z.object({
    _id: z.string(),
    title: z.string().nullable(),
    releaseDate: z.string().nullable(),
    _updatedAt: z.string()
}));

export const sanityLiveLoadermovieEntryQueryResultSchema = z.object({
    _id: z.string(),
    title: z.string().nullable(),
    releaseDate: z.string().nullable(),
    _updatedAt: z.string()
}).nullable();

export const sanityLiveLoaderpersonCollectionQueryResultSchema = z.array(z.object({
    _id: z.string(),
    name: z.string().nullable(),
    _updatedAt: z.string()
}));

export const sanityLiveLoaderpersonEntryQueryResultSchema = z.object({
    _id: z.string(),
    name: z.string().nullable(),
    _updatedAt: z.string()
}).nullable();

export const sanityLiveLoaderscreeningCollectionQueryResultSchema = z.array(z.object({
    _id: z.string(),
    movie: movieReferenceSchema.nullable(),
    screeningDate: z.null(),
    theater: z.null(),
    _updatedAt: z.string()
}));

export const sanityLiveLoaderscreeningEntryQueryResultSchema = z.object({
    _id: z.string(),
    movie: movieReferenceSchema.nullable(),
    screeningDate: z.null(),
    theater: z.null(),
    _updatedAt: z.string()
}).nullable();

export const sanityClientSanityQueriesSchema = z.object({
    "*[_type == \"movie\"] | order(_updatedAt desc){_id,title,releaseDate,_updatedAt}": sanityLiveLoadermovieCollectionQueryResultSchema,
    "*[_type == \"movie\" && _id == $id][0]{_id,title,releaseDate,_updatedAt}": sanityLiveLoadermovieEntryQueryResultSchema,
    "*[_type == \"person\"] | order(name asc){_id,name,_updatedAt}": sanityLiveLoaderpersonCollectionQueryResultSchema,
    "*[_type == \"person\" && _id == $id][0]{_id,name,_updatedAt}": sanityLiveLoaderpersonEntryQueryResultSchema,
    "*[_type == \"screening\"] | order(screeningDate asc){_id,movie,screeningDate,theater,_updatedAt}": sanityLiveLoaderscreeningCollectionQueryResultSchema,
    "*[_type == \"screening\" && _id == $id][0]{_id,movie,screeningDate,theater,_updatedAt}": sanityLiveLoaderscreeningEntryQueryResultSchema
});

export const allSanitySchemaTypesSchema = z.union([personReferenceSchema, crewMemberSchema, castMemberSchema, plotSummariesSchema, plotSummarySchema, sanityImageAssetReferenceSchema, blockContentSchema, movieReferenceSchema, sanityFileAssetReferenceSchema, screeningSchema, geopointSchema, personSchema, sanityImageCropSchema, sanityImageHotspotSchema, slugSchema, movieSchema, sanityImagePaletteSwatchSchema, sanityImagePaletteSchema, sanityImageDimensionsSchema, sanityImageMetadataSchema, sanityFileAssetSchema, sanityAssetSourceDataSchema, sanityImageAssetSchema]);
