---
name: Prettier

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run:
    name: Can the code be prettier? 🤔
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*
      - run: corepack enable && pnpm --version
      - run: pnpm install --dev --ignore-scripts
      - uses: actions/cache@v4
        with:
          path: node_modules/.cache/prettier/.prettier-cache
          key: prettier-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm format
      - run: git restore .github/workflows
      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.ECOSPARK_APP_ID }}
          private-key: ${{ secrets.ECOSPARK_APP_PRIVATE_KEY }}
      - uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 # v5
        with:
          author: github-actions <41898282+github-actions[bot]@users.noreply.github.com>
          body: I ran `pnpm format` 🧑‍💻
          branch: actions/prettier
          commit-message: "chore(prettier): 🤖 ✨"
          labels: 🤖 bot
          title: "chore(prettier): 🤖 ✨"
          token: ${{ steps.generate-token.outputs.token }}
